@hostname = http://127.0.0.1
@port = 8000
@host = {{hostname}}:{{port}}
@baseUrl = {{host}}
@contentType = application/json

###

GET {{baseUrl}}/api-test/?country=GHCWDB HTTP/1.1
content-type: {{contentType}}

###