@contentType = application/json

@baseUrl = http://localhost:8080

# @name login
post {{baseUrl}}/login HTTP/1.1
content-type: {{contentType}}

{
  "username": "shubham",
  "password": "qwertyuiop[]\\"
}

###

@accessToken = {{login.response.body.token}}
@accessUsername = {{login.response.body.username}}
@accessAvatar = {{login.response.body.avatar}}

###
post {{baseUrl}}/checkToken HTTP/1.1
content-type: {{contentType}}

# Authorization: token {{accessToken}}

{
  "token": "{{accessToken}}"
}
###

post {{baseUrl}}/getHomeFeed HTTP/1.1
content-type: {{contentType}}


{
  "token": "{{accessToken}}"
}

###
post {{baseUrl}}/register HTTP/1.1
content-type: {{contentType}}

{
    
}
###

get {{baseUrl}}/post/5fc1d8b9446f4a590806c145 HTTP/1.1
content-type: {{contentType}}

###
post {{baseUrl}}/post/5fc1d8b9446f4a590806c145/edit HTTP/1.1
content-type: {{contentType}}


{
  "token": "{{accessToken}}"
}

###
delete {{baseUrl}}/post/:id HTTP/1.1
content-type: {{contentType}}



###
post {{baseUrl}}/create-post HTTP/1.1
content-type: {{contentType}}

{
  "token": "{{accessToken}}",
  "title": "Your Title",
  "body": "Your content lorem ipsum"
}

###
post {{baseUrl}}/search HTTP/1.1
content-type: {{contentType}}

###

post {{baseUrl}}/doesUsernameExist HTTP/1.1
content-type: {{contentType}}


{
  "username": "shubham"
}
###
post {{baseUrl}}/doesEmailExist HTTP/1.1
content-type: {{contentType}}

{
  "email": "shubhammr21@gmail.com"
}
###

post {{baseUrl}}/profile/{{accessUsername}} HTTP/1.1
content-type: {{contentType}}

###
get {{baseUrl}}/profile/{{accessUsername}}/posts HTTP/1.1
content-type: {{contentType}}

###
get {{baseUrl}}/profile/{{accessUsername}}/followers HTTP/1.1
content-type: {{contentType}}

###
get {{baseUrl}}/profile/{{accessUsername}}/following HTTP/1.1
content-type: {{contentType}}

###

post {{baseUrl}}/addFollow/shubhamm HTTP/1.1
content-type: {{contentType}}

{
  "token": "{{accessToken}}"
}
###
post {{baseUrl}}/removeFollow/shubhamm HTTP/1.1
content-type: {{contentType}}

{
  "token": "{{accessToken}}"
}
###
