# Generated by Django 3.1.7 on 2021-02-21 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210221_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
