# Generated by Django 3.1.7 on 2021-02-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_store_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='open_time',
        ),
        migrations.CreateModel(
            name='StoreHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('open_time', models.TimeField(blank=True)),
                ('close_time', models.TimeField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_hour', to='api.store')),
            ],
        ),
    ]
