# Generated by Django 3.1.7 on 2021-02-21 13:44

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210221_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='photos/', verbose_name='Photo'),
        ),
    ]
